[Tooltip_Options]
	#Allowed Values: DISABLE, ENABLE, SHIFT, DEBUG, SHIFT_AND_DEBUG
	burnTimeTooltip = "DISABLE"
	#Allowed Values: DISABLE, ENABLE, SHIFT, DEBUG, SHIFT_AND_DEBUG
	durabilityTooltipMode = "DISABLE"
	#Allowed Values: DISABLE, ENABLE, SHIFT, DEBUG, SHIFT_AND_DEBUG
	enchantabilityTooltipMode = "DISABLE"
	#Allowed Values: DISABLE, ENABLE, SHIFT, DEBUG, SHIFT_AND_DEBUG
	foodTooltipMode = "DISABLE"
	#Allowed Values: DISABLE, ENABLE, SHIFT, DEBUG, SHIFT_AND_DEBUG
	registryNameMode = "DISABLE"
	#Allowed Values: DISABLE, ENABLE, SHIFT, DEBUG, SHIFT_AND_DEBUG
	maxStackSizeTooltipMode = "DISABLE"
	#Allowed Values: DISABLE, ENABLE, SHIFT, DEBUG, SHIFT_AND_DEBUG
	tagsTooltipMode = "DISABLE"
	#Allowed Values: DISABLE, ENABLE, SHIFT, DEBUG, SHIFT_AND_DEBUG
	translationKeyTooltipMode = "DISABLE"
	#Allowed Values: DISABLE, ENABLE, SHIFT, DEBUG, SHIFT_AND_DEBUG
	dataComponentsMode = "DISABLE"
