#General settings for Just Enough Markers
[general]
	#Text used to filter recipes with an Recipe ID.
	#Recipes with an Recipe ID containing this text will display the marker
	# Default: kubejs
	recipeIdFilter = "kubejs"
	#List of item IDs for recipes WITHOUT an ID that should display the marker
	# Format: ["modId:item"]
	# Example: ["mysticalagriculture:inferium_seeds", "ironsspellbooks:fireball_scroll"]
	outputFilter = []
	#First line of the tooltip when hovering over the marker
	# Default: Modified recipe
	tooltipLine1 = "Modified recipe"
	#Second line of the tooltip when hovering over the marker
	# Default: According to the modpack creator
	tooltipLine2 = "According to the modpack creator"

#Debug settings for testing or development
[debug]
	#If true, the marker will display on all recipes (ignores filters)
	#Useful for testing or debugging
	# Default: false
	onlySpecificRecipeID = false
	#Default X offset for the marker if no category override exists
	# Default: 19
	# Range: -1000 ~ 1000
	defaultOffsetX = 19
	#Default Y offset for the marker if no category override exists
	# Default: -25
	# Range: -1000 ~ 1000
	defaultOffsetY = -25

#Custom offsets for specific recipe categories
[CustomOffsetsMarkerCategories]
	#Adjust marker position for specific recipe categories
	# Format: "categoryId;offsetX;offsetY"
	# Example: "minecraft;crafting;-14;-14", "ae2:charger;3;3"
	categories = ["minecraft:compostable;0;0", "minecraft:fuel;0;0", "apothic_enchanting:enchanting;5;5", "apothic_spawners:spawner_modifiers;0;0", "easy_villagers:breeding;0;-19", "easy_villagers:converting;0;-19", "easy_villagers:incubating;0;-19", "jei:information;0;-110", "jei_mekanism_multiblocks:multiblock.mekanism.boiler;-135;-110", "jei_mekanism_multiblocks:multiblock.mekanism.dynamic_tank;-135;-110", "jei_mekanism_multiblocks:multiblock.mekanism.evaporation_plant;-135;-110", "jei_mekanism_multiblocks:multiblock.mekanism.matrix;-135;-110", "jei_mekanism_multiblocks:multiblock.mekanism.sps;-135;-110", "jei_mekanism_multiblocks:multiblock.mekanismgenerators.fission_reactor;-135;-110", "jei_mekanism_multiblocks:multiblock.mekanismgenerators.fusion_reactor;-135;-110", "jei_mekanism_multiblocks:multiblock.mekanismgenerators.turbine;-135;-110", "mysticalagriculture:enchanter;20;0", "mysticalagriculture:reprocessor;20;0", "mysticalagriculture:soul_extractor;20;0", "mysticalagriculture:soulium_spawner;20;0", "tombstone:combine;20;0", "reliquary:infernal_tear;20;0", "mob_grinding_utils:solidify;20;0", "jeed:effect_info;0;-110", "justenoughbreeding:breeding;0;0", "powah:coolant;0;0", "powah:heat_source;0;0", "powah:magmatic;0;0", "powah:reactor_fuel;0;0", "powah:solid_coolant;0;0", "tiab:resource_generator;0;0", "chipped:workbench;0;-95", "cataclysm:weapon_infusion;20;0", "betterarcheology:identifying;-5;-5", "jeresources:dungeon;0;-110", "jeresources:enchantment;0;-115", "jeresources:mob;0;-115", "jeresources:plant;0;-115", "jeresources:villager;0;0", "jeresources:worldgen;0;-75", "aether:ambrosium_enchanting;20;0", "aether:block_placement_ban;20;0", "aether:item_placement_ban;20;0", "knightlib:great_chalice_interaction;0;0"]
